@startuml C1 Context
!pragma layout smetana
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

Person(merchant, "Merchant", "Uses Neuron to allow payments")
Person(client, "Client", "Pays for goods/services")

System(neuron, "Neuron", "Payment system")
System_Ext(tpp, "TPP", "Third-party payment provider")
System_Ext(bank, "Bank", "Client's bank")
System_Ext(merchantService, "Merchant's service")

Rel(merchant, neuron, "Integrates with")
Rel(client, neuron, "Pays with")
Rel(neuron, tpp, "Uses")
Rel(tpp, bank, "Integrates with")
Rel(client, bank, "Has account in")
Rel(client, merchantService, "Buys goods/services at")

LAYOUT_WITH_LEGEND()
@enduml
